### ISSUE TITLE
Provide an exception type for unknown methods

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh-cpi-ruby#5]
The ruby CPI returns currently an error from type `InvalidCall` for methods which are not known. This error is returned also for other failures e.g. `JSON::ParserError`. This makes it hard on BOSH side to introduce new methods and ignore CPIs which don't know anything about the new method. Therefore, there should be a more specific error type for unknown methods.

**Comment by voelzmo** [comment]
I guess this is fixed by https://github.com/cloudfoundry/bosh-cpi-ruby/commit/088db0391e2217d800bfefd345c0d8ef2f1fcc90
