### ISSUE TITLE
confused by the wrong number of arguments

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-cpi-ruby#6]
To bump the version of `bosh_cpi` from `1.x` to `2.1.1`, I got the following error.
```
CPI 'has_vm' method responded with error: CmdError{"type":"InvalidCall","message":"Arguments are not correct, details: 'wrong number of arguments (1 for 0)'","ok_to_retry":false}
```

After investigations, the root cause is that cpi_lambda has to add a new argument `context`. But from the above error message, it seems that `has_vm` missed an argument. It's confusing. So, opened this issue in case someone else also hits it.

**Comment by nehagjain15** [comment]
@bingosummer Thank you, but we do have that https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/b71ec593818b610e3ae48a7a62d539b4860ec4bf/src/vsphere_cpi/bin/vsphere_cpi#L24

**Comment by bingosummer** [comment]
bosh_cpi v2.1.1 added `context`. v2.5.0 added another parameter `cpi_api_version`.
https://github.com/cloudfoundry/bosh-cpi-ruby/blob/v2.5.0/lib/bosh/cpi/cli.rb#L87
So, I think, we need to add another new parameter in cpi_lambda.

**Comment by pivotal-jamil-shamy** [comment]
cc @xtreme-andrew-su

**Comment by xtreme-andrew-su** [comment]
@bingosummer @nehagjain15 Adding the `cpi_api_version` to your lambda should be sufficient. It is intended for when you want to support version 2 of the API contracts. (see: https://github.com/cloudfoundry/bosh-notes/blob/master/proposals/registry-removal.md)

**Comment by nehagjain15** [comment]
@xtreme-andrew-su thank you for the link.
